### ISSUE TITLE
how do I deploy to heroku?

### ISSUE THREAD

**Issue by Connoropolous** [ThoughtWorksInc/stonecutter#6]
I've taken many of the steps, but I keep ending up in this situation: 

[main] INFO org.eclipse.jetty.server.Server - Started @5418ms
2016-02-09T01:15:36.007955+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

can someone give me a hand?

**Comment by aewelch** [comment]
We're not able to recreate your error. How are you deploying?

The latest code is always on the [D-CENT fork](https://github.com/d-cent/stonecutter). If you haven't already, could you try again with the latest code from there?

**Comment by Connoropolous** [comment]
I was trying to deploy using the deploy_heroku.sh script. And yeah, I was working with the DCENT fork. Could you write up what the steps are that ThoughtWorks would take to deploy to heroku? I know that there are a bunch of running instances of it running on heroku.

**Comment by aewelch** [comment]
Thanks for bringing this to our attention. We currently deploy Stonecutter to a few Digital Ocean Droplets using Docker. The `deploy_heroku.sh` script isn't being maintained, so we'll remove it. We don't currently recommend using Heroku since it doesn't play well with Docker, or Clojure.

Is us not supporting Heroku a barrier for you trying out the application? Are there any other cloud platforms you would consider?

**Comment by Connoropolous** [comment]
Cool! I'm just investigating digital ocean. Is there a document that I
could go off of I was trying to deploy stonecutter to digital ocean, and
hadn't used docker before. I see there is stuff in the readme about it, but
it still feels a bit daunting.

**Comment by aewelch** [comment]
All the documentation about deploying using Docker is in the readme. Is there anything in particular which is unclear or intimidating? We've tried to make it as easy to follow as possible, so we'd be interested to know.

**Comment by Connoropolous** [comment]
With the help of a friend I managed to get an instance of stonecutter running on a digital ocean droplet :+1: 

One issue that I had was that it wasn't mounting (using `-v`) directories... it would only mount specific files, in the case of the nginx and stonecutter containers, so I had to list them each individually.
